# Generated by Django 4.2 on 2024-04-22 23:09

from django.db import migrations, models
import django.db.models.deletion
import reservationsapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("reservationsapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dateresa",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de la réservation"
                    ),
                ),
                (
                    "if_number",
                    models.CharField(
                        default=reservationsapp.models.generate_if_number,
                        max_length=6,
                        unique=True,
                        verbose_name="Numéro de la réservation",
                    ),
                ),
                (
                    "seat_number",
                    models.IntegerField(default=1, verbose_name="Numéro de place"),
                ),
                (
                    "car_number",
                    models.IntegerField(default=1, verbose_name="Numéro de voiture"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservationsapp.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "passager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservationsapp.passenger",
                        verbose_name="Passager",
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservationsapp.trajet",
                        verbose_name="Trajet",
                    ),
                ),
            ],
        ),
    ]
