# Generated by Django 4.2 on 2024-05-06 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservationsapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
        migrations.RemoveField(
            model_name="client",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="last_name",
        ),
    ]
