# Generated by Django 4.2 on 2024-05-03 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservationsapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="car_number",
            new_name="car",
        ),
    ]
