# Generated by Django 4.2 on 2024-04-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservationsapp", "0002_client_passenger_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="name",
        ),
        migrations.RemoveField(
            model_name="passenger",
            name="email",
        ),
        migrations.RemoveField(
            model_name="passenger",
            name="name",
        ),
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.CharField(default="", max_length=255, verbose_name="Adresse"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(
                default="Prénom", max_length=100, verbose_name="Prénom"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(
                default="Prénom", max_length=100, verbose_name="Nom"
            ),
        ),
        migrations.AddField(
            model_name="passenger",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AddField(
            model_name="passenger",
            name="first_name",
            field=models.CharField(
                default="Prénom", max_length=100, verbose_name="Prénom"
            ),
        ),
        migrations.AddField(
            model_name="passenger",
            name="last_name",
            field=models.CharField(default="Nom", max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
    ]
