# Generated by Django 4.2 on 2024-05-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservationsapp", "0002_rename_car_number_ticket_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gare",
            name="station_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
