# Generated by Django 4.2 on 2024-04-23 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservationsapp", "0003_remove_client_name_remove_passenger_email_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Passenger",
            new_name="Passager",
        ),
    ]
