# Generated by Django 4.2 on 2024-05-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservationsapp", "0004_rename_gare_station"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
        migrations.RemoveField(
            model_name="client",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="journey",
            name="arrival_date_time",
            field=models.DateTimeField(help_text="Date et heure d'arrivée"),
        ),
        migrations.AlterField(
            model_name="journey",
            name="departure_date_time",
            field=models.DateTimeField(help_text="Date et heure de départ"),
        ),
    ]
