# Generated by Django 4.2 on 2024-04-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reservationsapp", "0006_passager_user_alter_client_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="passager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="reservationsapp.passager",
                verbose_name="Passager",
            ),
        ),
    ]
