# Generated by Django 4.2 on 2024-04-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservationsapp", "0007_alter_reservation_passager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="car_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Numéro de voiture"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="seat_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Numéro de place"
            ),
        ),
    ]
