# Generated by Django 4.2 on 2024-04-29 13:26

from django.db import migrations, models
import django.db.models.deletion
import reservationsapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("reservationsapp", "0008_alter_reservation_car_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="car_number",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="passager",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="seat_number",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="trajet",
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "if_number",
                    models.CharField(
                        default=reservationsapp.models.generate_if_number,
                        max_length=6,
                        unique=True,
                        verbose_name="Numéro du ticket",
                    ),
                ),
                (
                    "car_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Numéro de voiture"
                    ),
                ),
                (
                    "seat",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Numéro de place"
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="reservationsapp.journey",
                        verbose_name="Trajet",
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="reservationsapp.passager",
                        verbose_name="Passager",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="reservationsapp.reservation",
                        verbose_name="Réservation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reservation",
            name="trajet",
            field=models.ManyToManyField(
                related_name="reservations",
                to="reservationsapp.trajet",
                verbose_name="Trajet",
            ),
        ),
    ]
