# Generated by Django 4.2 on 2024-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsapp', '0010_route_rename_nomgare_gare_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='arrival_date_time',
            field=models.DateTimeField(help_text="Date et heure d'arrivée"),
        ),
        migrations.AlterField(
            model_name='journey',
            name='departure_date_time',
            field=models.DateTimeField(help_text='Date et heure de départ'),
        ),
    ]
